### ISSUE TITLE
Uso de outra interface para o CustomResourceDefinition

### ISSUE THREAD

**Issue by lukerops** [lukerops/tf-gapi#1]
Hoje o projeto usa a mesmo interface do Kubernetes para o `CustomResourceDefinition`, porém, chegamos aos seguintes problemas:
- Vários campos não são suportados;
- Por questões de limitação do HCL, o schema é mais limitado, não sendo tão poderoso quanto ao do Kubernetes;
- Alguns campos possuem valores/nomes que não fazem sentido no contexto desse projeto (ex: `scope: Cluster`).

Devido a esses pontos é melhor criar um schema novo para o `CustomResourceDefinition`.

**Comment by lukerops** [comment]
Após remover alguns campos que não fazem sentido no contexto do projeto, cheguei ao seguinte schema:
```yaml
apiVersion: tf-gapi.lukerops.com/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: <lowercase-kind>.<group>
spec:
  group: string
  kind: CamelCasedKind
  versions:
    - name: v1alpha1
      enabled: true
      deprecated: false
      specSchema:
        type: object
        properties:
          string:
            type: string
            minLength: 0
            maxLength: 50
            pattern: regex
          integer:
            type: integer
            minimum: 0
            maximum: 50
          bool:
            type: bool
          array:
            type: array
            minItems: 0
            maxItems: 10
            items:
              type: string | integer | object
          object:
            type: object
            properties:
              property:
                type: string | integer
          defaultParams:
            description: string
            externalDocs: string
```

Nessa proposta, temos o campo `deprecated` que indicará quando uma versão foi depreciada, e com isso, quando for utilizada, um alerta será mostrado no `plan`, mas sem causar erro. Apenas o uso de versões desabilitadas (`enabled: false`) ocasionarão em um erro.
