### ISSUE TITLE
Implementar default value para campos primitivos (integer, string, bool)

### ISSUE THREAD

**Issue by daltonmatos** [lukerops/tf-gapi#16]
A ideia é podermos definir um valor default para um campo qualquer. Essa possibilidade habilitará o uso de campo opcionais em um manifesto. Muitas vezes facilitando a escrita desse yaml.

## Proposta
```yaml
apiVersion: tf-gapi.lukerops.com/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: serviceaccount.gcp.iam.stone.co
spec:
  group: gcp.iam.stone.co
  kind: ServiceAccount
  versions:
    - name: v1alpha1
      specSchema:
        type: object
        properties:
          id:
            type: string
          create:
            type: bool
            default: false
```

Acima uma proposta de como esse valor pode ser definido. Junto com o campo `type:` teríamos o campo `default:` com o valor padrão para esse campo.

### Pontos de atenção

- Se tiver sido definido o campo `default:` ele **precisa** ter um valor. Não podemos definir um default vazio;
- Validar para confirmar que o valor default é compatível com o campo recebendo esse default. Por ex: Não podemos definir `default: true` para um campo `type: integer`;
- Avaliar se faz sentido ter valor default para `type: object` e `type: array`. Talvez array até seja comum ter `default: []`, talvez seja mais comum do que `defaul: {}` para `type: object`. 
   - Um exemplo de defualt para array é a definição de uma role sem permissões adicionais. Nesse caso o campo de permissões poderia ser `default: []`.
